### ISSUE TITLE
Win32crypt

### ISSUE THREAD

**Issue by shittyfollower** [FallenAstaroth/stink#15]
When running the .py file it works fine. However once the .exe is compiled get the following error:

Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONE955~1\test.py", line 1, in <module>
    from stink.multistealer import Stealer
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONE955~1\stink\multistealer.py", line 6, in <module stink.multistealer>
  File "C:\Users\ADMINI~1\AppData\Local\Temp\ONE955~1\stink\browsers\chrome.py", line 9, in <module stink.browsers.chrome>
ImportError: LoadLibraryExW 'C:\Users\ADMINI~1\AppData\Local\Temp\ONE955~1\win32crypt.pyd' failed: The specified module could not be found.

**Comment by FallenAstaroth** [comment]
Did you perform all the actions through the regular Window's terminal?
I have updated the instructions for compiling through the Windows console.

https://github.com/FallenAstaroth/stink/blob/master/docs/en.md#CMD

**Comment by shittyfollower** [comment]
I did yes, using Nuitka
Ok thanks I will try using these instructions

**Comment by shittyfollower** [comment]
Thank you that worked perfectly.

**Comment by jaday88** [comment]
Hi, I have a problem not installing stink==0.0.5 Also can't find the folder at this path In the appearing folder venv go to the path \Lib\site-packages\win32\.
Copy the file win32crypt.pyd

**Comment by FallenAstaroth** [comment]
> Hi, I have a problem not installing stink==0.0.5 Also can't find the folder at this path In the appearing folder venv go to the path \Lib\site-packages\win32. Copy the file win32crypt.pyd

Hi. What error does it throw when trying to set stink=0.0.5? The folder will appear after installing stink.
