### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by FallenAstaroth** [FallenAstaroth/stink#16]
Hi, I have a problem not installing stink==0.0.5 Also can't find the folder at this path In the appearing folder venv go to the path \Lib\site-packages\win32\.
Copy the file win32crypt.pyd

_Originally posted by @jaday88 in https://github.com/FallenAstaroth/stink/issues/15#issuecomment-984507501_

**Comment by FallenAstaroth** [comment]
> Hi, I have a problem not installing stink==0.0.5 Also can't find the folder at this path In the appearing folder venv go to the path \Lib\site-packages\win32. Copy the file win32crypt.pyd
> 
> _Originally posted by @jaday88 in [#15 (comment)](https://github.com/FallenAstaroth/stink/issues/15#issuecomment-984507501)_

The problem was in the Python version. Recommended versions are >=3.7 and <=3.9

**Comment by FallenAstaroth** [comment]
If you have 2 or more versions of python installed, you need to specify which version you want to use when creating the virtual environment.
For example ```virtualenv -p "c:\users\wolf in chains\appdata\local\programs\python\python38\python.exe" venv```

**Comment by CARDANA22** [comment]
that didn't work for me

**Comment by FallenAstaroth** [comment]
> that didn't work for me

Throw the full error you are getting

**Comment by CARDANA22** [comment]
With python 3.9.9 and in pipenv and python 3.8
ERROR: Could not find a version that satisfies the requirement pywin32<303,>=302 (from stink)
ERROR: No matching distribution found for pywin32<303,>=302

**Comment by FallenAstaroth** [comment]
> With python 3.9.9 and in pipenv and python 3.8 ERROR: Could not find a version that satisfies the requirement pywin32<303,>=302 (from stink) ERROR: No matching distribution found for pywin32<303,>=302

What operating system do you have? This stealer is for Windows only.
