### ISSUE TITLE
Не удаётся установить.

### ISSUE THREAD

**Issue by WhiteTea1** [FallenAstaroth/stink#17]
Привет, когда я пытаюсь установить stink (последняя версия на момент 4 ноября). Ошибка в pywin32 
```

ERROR: Cannot install stink==0.0.1, stink==0.0.2, stink==0.0.3, stink==0.0.4, stink==0.0.5, stink==0.0.6 and stink==0.0.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    stink 0.0.7 depends on pywin32==301
    stink 0.0.6 depends on pywin32==301
    stink 0.0.5 depends on pywin32==301
    stink 0.0.4 depends on pywin32==301
    stink 0.0.3 depends on pywin32==301
    stink 0.0.2 depends on pywin32==301
    stink 0.0.1 depends on pywin32==301

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

Python version: 3.0.10

что с этим делать?

**Comment by FallenAstaroth** [comment]
> Привет, когда я пытаюсь установить stink (последняя версия на момент 4 ноября). Ошибка в pywin32
> 
> ```
> 
> ERROR: Cannot install stink==0.0.1, stink==0.0.2, stink==0.0.3, stink==0.0.4, stink==0.0.5, stink==0.0.6 and stink==0.0.7 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     stink 0.0.7 depends on pywin32==301
>     stink 0.0.6 depends on pywin32==301
>     stink 0.0.5 depends on pywin32==301
>     stink 0.0.4 depends on pywin32==301
>     stink 0.0.3 depends on pywin32==301
>     stink 0.0.2 depends on pywin32==301
>     stink 0.0.1 depends on pywin32==301
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> ```
> 
> Python version: 3.0.10
> 
> что с этим делать?

pywin32 поддерживает Python 3.6 и выше. Рекомендуется установить пайтон >=3.7 и <=3.9.

**Comment by WhiteTea1** [comment]
ладно спасибо

**Comment by WhiteTea1** [comment]
проблема всё равно появлется

**Comment by FallenAstaroth** [comment]
> проблема всё равно появлется

При 2 и более установленных версиях python на этапе создания виртуального окружения нужно указывать какую конкретно вы хотите использовать. 
Например ```virtualenv -p "c:\users\wolf in chains\appdata\local\programs\python\python38\python.exe" venv```
