### ISSUE TITLE
problem with cookies

### ISSUE THREAD

**Issue by Bahafin677** [FallenAstaroth/stink#18]
cookies are not imported, how to import? I try it through the editor cookie, and the cookie bro does not work

**Comment by FallenAstaroth** [comment]
> cookies are not imported, how to import? I try it through the editor cookie, and the cookie bro does not work

While cookies are not designed for standard / third-party import methods, you need to configure them yourself to the right format. This will be fixed in an upcoming update.

**Comment by FallenAstaroth** [comment]
> any updates?

Due to events in Ukraine (of which I am a citizen) updates are postponed indefinitely

**Comment by FallenAstaroth** [comment]
Due to the inability to cover all import methods, it was decided to increase the number of fields to be searched to the maximum and provide formatting of the received files at your discretion.
