### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by JOJO-men** [FallenAstaroth/stink#20]
I am using windows 7 32bit and when running the code it gives such an error and the message in the telegram does not come
[SENDER]: MaxRetryError("HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5293900402:AAH9D6Vye21VZwCgLaqFPK_96ZbTYUMmwtQ/sendDocument (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))",)
[]
None
---------------------------------------------------------------------------------------------------------------------------------------------------
Я использую windows 7 32bit и при запуске кода выдаёт такую ошибку и сообщение в телеграмме не приходит
[SENDER]: MaxRetryError("HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5293900402:AAH9D6Vye21VZwCgLaqFPK_96ZbTYUMmwtQ/sendDocument (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))",)
[]
None

**Comment by FallenAstaroth** [comment]
> ## I am using windows 7 32bit and when running the code it gives such an error and the message in the telegram does not come
> [SENDER]: MaxRetryError("HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5293900402:AAH9D6Vye21VZwCgLaqFPK_96ZbTYUMmwtQ/sendDocument (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))",)
> []
> None
> Я использую windows 7 32bit и при запуске кода выдаёт такую ошибку и сообщение в телеграмме не приходит [SENDER]: MaxRetryError("HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5293900402:AAH9D6Vye21VZwCgLaqFPK_96ZbTYUMmwtQ/sendDocument (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)'),))",) [] None

Try to disable certificate validation.

If you are using a virtual environment:
Open the project directory and open the file `venv/Lib/site-packages/stink/utils/sender.py`

If not, open the directory where you have Python installed and open the file `Lib/site-packages/stink/utils/sender.py`

Then change the line in it from the screenshot to this `http = poolmanager.PoolManager(cert_reqs="CERT_NONE")`

**Comment by JOJO-men** [comment]
Thanks! It helped

**Comment by FallenAstaroth** [comment]
The `http = poolmanager.PoolManager()` has been moved to line 9 in the paths `venv/Lib/site-packages/stink/utils/config.py` and `Lib/site-packages/stink/utils/config.py` respectively
