### ISSUE TITLE
Стилит только эдж

### ISSUE THREAD

**Issue by YandereKiller** [FallenAstaroth/stink#22]
Привет, я тестил твой стиллер на нескольких компах, и на всех он без проблем стилит данные только с эджа, с остальных браузеров получается лишь куки вытащить. Хотелось бы узнать, получалось ли вытащить данные из других браузеров, либо это все ситуативно и зависит от системы. Понимаю, что многие функции еще в разработке, но просто в описании указана поддержка многих браузеров, а по факту работает только эдж. А в целом проект весьма интересный, удачи в разработке)

**Comment by YandereKiller** [comment]
(https://user-images.githubusercontent.com/101664012/158664716-795049e0-680e-4d41-8071-988b9d692c4d.jpg)
Вывод ошибок я с самого начала включил, и в консоли мне просто писало что не найдены пароли в браузерах, хотя они там записаны (Тестировал на Windows 10 и 11)

**Comment by YandereKiller** [comment]
Небольшая поправочка. Опера и брейв работают, но вот гугл вообще никак не хочет распознавать

**Comment by FallenAstaroth** [comment]
> Небольшая поправочка. Опера и брейв работают, но вот гугл вообще никак не хочет распознавать

Какая версия гугла? Там не так давно изменили место хранения, я его добавил как альтернативный путь, но мало ли. Теперь получается что только гугл не работает? Все остальные браузеры нормально считываются?

**Comment by YandereKiller** [comment]
Версия гугла 99.0.4844.51. Да, все остальные браузеры считываются без проблем, дискорд тоже

**Comment by FallenAstaroth** [comment]
> Версия гугла 99.0.4844.51. Да, все остальные браузеры считываются без проблем, дискорд тоже

В одной из этих директорий есть файл с название Cookies?
`C:\Users\Имя вашего пк\AppData\Local\Google\Chrome\User Data\Default`
`C:\Users\Имя вашего пк\AppData\Local\Google\Chrome\User Data\Default\Network`

**Comment by FallenAstaroth** [comment]
> Не находит именно пароли, куки крадет прекрасно. Да, файл с таким названием есть

А, ну если проблема с паролями, тогда проверьте существует ли файл `C:\Users\Имя вашего пк\AppData\Local\Google\Chrome\User Data\Default\Login Data` и не пустой ли он (хотя бы по весу файла). Все пароли гугл хранит в нем.

**Comment by YandereKiller** [comment]
Не, файл не пустой. Если его открыть, там как раз видно что зашифрованные пароли лежат, да и в гугле у меня есть сохраненные пароли, в общем странная тема

**Comment by FallenAstaroth** [comment]
> Не, файл не пустой. Если его открыть, там как раз видно что зашифрованные пароли лежат, да и в гугле у меня есть сохраненные пароли, в общем странная тема

Да, странная хрень, мб пароли старые и он их расшифровать не может? У меня тоже некоторые пароли так терялись. Можно новый добавить и потестить.

**Comment by FallenAstaroth** [comment]
Скорее всего проблема была связана с профилями браузера. Поддержка мультипрофилей добавлена начиная с версии 1.2.2.
