### ISSUE TITLE
Chrome profile 

### ISSUE THREAD

**Issue by TMQrX** [FallenAstaroth/stink#24]
when there is more than one profile on browser like google chrome, it can't get all cookies and passwords in all those profiles. So, hope you will fix it in the next update. Thank you!

**Comment by FallenAstaroth** [comment]
> when there is more than one profile on browser like google chrome, it can't get all cookies and passwords in all those profiles. So, hope you will fix it in the next update. Thank you!

Support for multiprofiles has been added since version 1.2.2
