### ISSUE TITLE
Can I send commands from a telegram?

### ISSUE THREAD

**Issue by FallenAstaroth** [FallenAstaroth/stink#26]
@domofon4ik
Questions should be asked in this section. It was funny to go to your profile and see the question in the description of the forked repository)

The answer to your question:
No, that's not how it works. When you run the stealer, it collects data and sends it as an archive to the telegram you specified. If you need help, specify at what stages the problems occurred.

**Comment by Saraana1** [comment]
Can you help me with cookies? The cookies that stink collects are not accepted by browser cookie extensions. Do they need to be converted to another format?
