### ISSUE TITLE
Cookies problem

### ISSUE THREAD

**Issue by Saraana1** [FallenAstaroth/stink#27]
Can you help me with cookies? The cookies that stink collects are not accepted by browser cookie extensions. Do they need to be converted to another format?

**Comment by FallenAstaroth** [comment]
> Can you help me with cookies? The cookies that stink collects are not accepted by browser cookie extensions. Do they need to be converted to another format?

https://github.com/FallenAstaroth/stink/issues/25#issuecomment-1091125327

**Comment by Saraana1** [comment]
Спасибо за ответ. Завтра попробую написать конвертер под нужный формат, ибо на просторах интернета не нашел. По ветке понял что я не один такой) Если получится, то выложу в открытый доступ. Благодарю за ваши старания!

**Comment by FallenAstaroth** [comment]
> Спасибо за ответ. Завтра попробую написать конвертер под нужный формат, ибо на просторах интернета не нашел. По ветке понял что я не один такой) Если получится, то выложу в открытый доступ. Благодарю за ваши старания!

Ну, думаю это не сложно, учитывая что из базы вытягиваются все ключи, то проблем возникнуть не должно. Максимум что будет отличаться это названия этих самых ключей ключей. Удачи, ждём конвертер)

**Comment by Saraana1** [comment]
Обещанный конвертер. Не судите строго, в питоне новичок)
https://github.com/Saraana1/Stink-cookie-converter

**Comment by FallenAstaroth** [comment]
> Обещанный конвертер. Не судите строго, в питоне новичок) https://github.com/Saraana1/Stink-cookie-converter

Ну если новичок, то простительно) Главное что работает. В гугле у меня импортнулись куки, в других не проверял. Под другие браузеры формат подходит или там тоже ключи менять надо?

**Comment by Saraana1** [comment]
Проверял для Chrome и Edge, остальные проверю позже. Если что, то обновлю
