### ISSUE TITLE
Way to execute anything with the installed payload?

### ISSUE THREAD

**Issue by XMVZ** [FallenAstaroth/stink#28]
I would like to execute a new payload using the installed Stink exe.
Is this possible via Telegram? 
Can I do remote shell or execute new exe?

Thanks

**Comment by XMVZ** [comment]
It's very urgent that I'm able to do this if you can reach out to me or drop your Telegram let me nkow!

**Comment by FallenAstaroth** [comment]
> I would like to execute a new payload using the installed Stink exe. Is this possible via Telegram? Can I do remote shell or execute new exe?
> 
> Thanks

Hi. Stink does not have this functionality and there are no plans to introduce it in the future. 

This is already a remote access functionality, and Stink is positioned as a styler. But such a program is already in development, the only thing is that the exact timing of the first version is unknown, as there is almost no time for pet projects.
