### ISSUE TITLE
How to use Session data Telegram

### ISSUE THREAD

**Issue by TMQrX** [FallenAstaroth/stink#31]
How to use the session data that stink collected, may change it to tdata? thank you.

**Comment by FallenAstaroth** [comment]
> How to use the session data that stink collected, may change it to tdata? thank you.

1. [Download](https://telegram.org/dl/desktop/win_portable) Telegram Portable.
2. Unzip archive and open Telegarm folder.
3. Run `Telegarm.exe` and close it immediately.
4. In the appeared folder `tdata` delete all the files and transfer to it the files from the archive, which sent the stilter.
5. Run` Telegarm.exe` again.
