### ISSUE TITLE
Процесс завершился с кодом 0x00000001

### ISSUE THREAD

**Issue by WhiteWolfDD** [FallenAstaroth/stink#32]
Изменил проект под себя, добавил **antiVM** модуль, добавил **Steam** модуль, удалил **Autostart** и подправил некоторые моменты.
С последним обновлением **Windows 11** они поставили по умолчания за место **cmd**, **Windows Terminal**.
Сам проект работает, скидывает все файлы которые требуются, завершается в **PyCharm**, **Visual Studio** с кодом 0, но открывает **2 окна Windows Terminal** и выводит сообщение "**[Процесс завершил работу с кодом 1 (0x00000001)]**".
Очень бы хотелось **связаться с тобой лично** для выяснения и решения этой проблемы, так-же, если нужно, мог бы скинуть свою версию "stink".

*2 окна Windows Terminal*
![изображение_2022-07-25_020638589](https://user-images.githubusercontent.com/71248043/180669474-76310915-bd74-41c3-878b-16fcbb8cfb69.png)

*Код завершения в Visual Studio*
![изображение_2022-07-25_021013966](https://user-images.githubusercontent.com/71248043/180669572-eaec01d7-662f-4908-a84c-c5f17baa7e20.png)

*Код завершения в PyCharm*
![изображение_2022-07-25_021135280](https://user-images.githubusercontent.com/71248043/180669602-5f3acbd2-0165-4c5c-a362-8ca5f283156f.png)

**Comment by WhiteWolfDD** [comment]
Так-же хотел бы добавить, что через **Nuitka** скрывается консоль cmd. Компилирую по инструкции
_Nuitka --onefile --windows-disable-console **.py_
При открытых окнах Windows Terminal папка onefile_... созданная при запуске exe остаётся в директории Temp и папка Stink в директории AppData. Из-за этого они доступны для прочтения Windows Defender

**Comment by FallenAstaroth** [comment]
> Так-же хотел бы добавить, что через **Nuitka** скрывается консоль cmd, но открываются 2 окна Windows Terminal. Компилирую по инструкции _Nuitka --onefile --windows-disable-console **.py_ При открытых окнах Windows Terminal папка onefile_... созданная при запуске exe остаётся в директории Temp и папка Stink в директории AppData. Из-за этого они доступны для прочтения Windows Defender

Насколько мне известно Nuitka сейчас не обладает функционалом скрытия Windows Terminal. Можно попробовать следующие варианты:

- изменить формат файла на `.pyw`
- скрыть окно при помощи `pywin32`
- скрыть окно при помощи `subprocess`

К сожалению сейчас нет возможности протестировать все на Windows 11, а на 10 Windows Terminal нельзя выставить по умолчанию.

Изменить расположение ` onefile_...` можно при помощи [флага](https://nuitka.net/doc/user-manual.html#use-case-4-program-distribution) `--windows-onefile-tempdir-spec`. Путь к директории `stink` можно сменить по пути `stink/utils/config.py` в переменной StoragePath класса MultistealerConfig (мало смысла изменять его если в системе нет директорий, которые добавлены в исключения Windows Defender).

**Comment by WhiteWolfDD** [comment]
С Windows Terminal достаточно много возни, код может работать и по принципу правильно написан, но с каких-то мне непонятных пор, этот-же код для Windows считается нерабочим. Конечно не могу на 100% утверждать свои-же слова, но как я понял, именно так всё на самом деле.
Пришлось немного изменить свой рабочий код и более не выплывает окна Windows Terminal.

А если по делу, то в вашем коде есть маленькие, но значительные проблемы. Если на устройстве **Telegram** или **FileZilla** установлены на другом диске (_Не на системном_), то программа не может его найти соответственно. Не могу сказать про браузеры, их не проверял.
У меня есть код на проверку нахождения директории через регистр, так-же можно написать на **FileZilla**, на **Telegram** увы никак, он не хранит данную информацию в регистре.
Я думаю в будущих обновлениях Вы найдёте решение данной проблемы без значительной потери времени на поиск системой данных путей.

*Код для стима*
![изображение_2022-07-26_222212959](https://user-images.githubusercontent.com/71248043/181094122-3f28cff8-de19-4414-a889-f42946a8eadf.png)

*Проверка существования пути*
![изображение_2022-07-26_222405197](https://user-images.githubusercontent.com/71248043/181094535-ca3060be-b5d9-424f-a0f1-03c3804d7f6d.png)

**Comment by FallenAstaroth** [comment]
Спасибо за совет. 

Странно что ошибка возникает при попытке считывания пути, ведь проверка на его существование прописана и прерывает выполнение функции случае его отсутствия. 

Не знаю как на счет Telegram и FileZilla (проверю позже), но браузеры всегда хранят свои данные по указаному в конфиге пути, отличаться может директория установки самого браузера, но не его данных.

**Comment by WhiteWolfDD** [comment]
Слежу за Вашими изменениями и "устанавливаю" последние версии Вашего проекта.
Для меня так-же странно было, что проверка есть на существование пути, но она по видимому не работает с WinReg.
Я не разбирался во всех нюансах, не стал полноценно отлаживать код для более правильного скрипта и написал новую проверку, которая в данном случае работает с WinReg.

Что касается Telegram и FileZilla, то с ними проверка пути происходит точно, без ошибок.
Discord скрипт удалил из-за ненадобности.
Так-же автозагрузка не работает на Windows 11. Может стоит запрет в данной версии Windows, может ещё что, так-же не разбирался из-за ненадобности. Запускал как с админ правами, так и без, безрезультатно.

В принципе это наверное всё, что касается новой версии Windows и её проблемами с данной программой. Если найду ещё какие-то проблемы в будущем, так-же отпишу 👍🏻
