### ISSUE TITLE
This..

### ISSUE THREAD

**Issue by n4stl3** [FallenAstaroth/stink#34]
![Snímek obrazovky 2022-09-04 203640](https://user-images.githubusercontent.com/112785354/188328408-80a5f3cf-fda0-4715-ac7f-b142f7c39e6e.png)

This shows up after i open exe file

**Comment by FallenAstaroth** [comment]
> ![Snímek obrazovky 2022-09-04 203640](https://user-images.githubusercontent.com/112785354/188328408-80a5f3cf-fda0-4715-ac7f-b142f7c39e6e.png)
> 
> This shows up after i open exe file

Did you do everything according to the instructions?

**Comment by n4stl3** [comment]
Yes i did everything, 3.9.0

**Comment by FallenAstaroth** [comment]
> Yes i did everything, 3.9.0

Before running the compilation, check if the win32 module is installed.

**Comment by n4stl3** [comment]
Yes i have win32 module downloaed, did it both ways with cmd and with BAT but it is still same

**Comment by FallenAstaroth** [comment]
> Yes i have win32 module downloaed, did it both ways with cmd and with BAT but it is still same

No errors or warnings during compilation?

It seems that this bug was encountered in older versions. Try installing a newer version of Nuitka.

**Comment by FallenAstaroth** [comment]
> Yes i have win32 module downloaed, did it both ways with cmd and with BAT but it is still same

You can also try specifying win32 in the compile command itself with `--include-package=pywin32`

**Comment by n4stl3** [comment]
I installed newest version of Nuitka (1.0.6), still same.. Dont know what to do.

**Comment by n4stl3** [comment]
When you compile the file.py
setting are :
Compress the file? Yes
Disable console? No
Right??

**Comment by n4stl3** [comment]
> > Yes i have win32 module downloaed, did it both ways with cmd and with BAT but it is still same
> 
> 
> 
> You can also try specifying win32 in the compile command itself with `--include-package=pywin32`

i dont understand where to put `--include-package=pywin32`

**Comment by FallenAstaroth** [comment]
> 

In compiling command `nuitka --onefile --plugin-enable=multiprocessing --include-package=pywin32 --windows-disable-console test.py`

**Comment by n4stl3** [comment]
thanls works
