### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by n4stl3** [FallenAstaroth/stink#36]
Will be in future antivir bypass?

**Comment by FallenAstaroth** [comment]
I have no experience in crypting files, but the topic is interesting, when I have time to read, maybe something will work.

About Windows Defender, it works once in a while and when recompiling (sometimes 2-3 times) it stops fighting with the file.

Also found an old build (about 3 months old) and uploaded it to VirusTotal, pretty good for a clean file without crypting:
![image](https://user-images.githubusercontent.com/47662957/188939075-68d63a23-3b66-4a4a-ba0e-f8f57fcda203.png)

**Comment by FallenAstaroth** [comment]
> I have no experience in crypting files, but the topic is interesting, when I have time to read, maybe something will work.
> 
> About Windows Defender, it works once in a while and when recompiling (sometimes 2-3 times) it stops fighting with the file.
> 
> Also found an old build (about 3 months old) and uploaded it to VirusTotal, pretty good for a clean file without crypting: ![image](https://user-images.githubusercontent.com/47662957/188939075-68d63a23-3b66-4a4a-ba0e-f8f57fcda203.png)

Funny thing is that after checking the file on VirusTotal I got 3 archives, all of them on Windows, which means that Defender missed them (I don't think it is disabled on the machines that check files)

**Comment by n4stl3** [comment]
Okay thx for respond
