### ISSUE TITLE
In some countries. telegram is not supported. blocked Therefore data cannot be sent to telegram bot

### ISSUE THREAD

**Issue by janedanyid** [FallenAstaroth/stink#41]
In some countries. telegram is not supported. blocked
Therefore data cannot be sent to telegram bot
How can I change this to upload data to ftp or hotmail email?

**Comment by FallenAstaroth** [comment]
You can create your own API server, then replace the Telegram API point with your own at the path stink.utils.sender.

An example of an API point for uploading files:
https://roytuts.com/python-flask-rest-api-file-upload/

Perhaps I will add an alternative way of sending in the future.

**Comment by janedanyid** [comment]
Do I need a server?

**Comment by janedanyid** [comment]
It was too hard. I have no computer skills.

**Comment by janedanyid** [comment]
Help me. Brother

**Comment by FallenAstaroth** [comment]
Here's a detailed guide on how to do it:
https://github.com/FallenAstaroth/stink/wiki/Sending-files-to-a-server

**Comment by janedanyid** [comment]
The telegram bot has now been modified to accept the file as its own api server.
Still need to create test.py？ entered the telegram ID/token yet？

How should it be compiled into an exe?

**Comment by FallenAstaroth** [comment]
If you have done everything as in the guide, Telegram is no longer affected here. You can write anything instead of a token and an id, they no longer apply. 

Otherwise, you do everything else as usual, including creating a test.py file. 

Compilation is done as in the usual version.

**Comment by janedanyid** [comment]
Confirm that it is correct. Upload in the server. no file found

**Comment by FallenAstaroth** [comment]
> Confirm that it is correct. server （Upload）. no file found How should I check?

The archive should arrive in the previously created uploads directory. Refresh the page if it is already open.

If the file did not come, then find the block from the screenshot below on the Web page and provide the contents of the Error log file.

![image](https://user-images.githubusercontent.com/47662957/219955867-4a21b576-8a61-4e9d-a69f-c2aa82cfc818.png)

**Comment by janedanyid** [comment]
Can over send successfully.
I tried again.
