### ISSUE TITLE
Collecting browser extensions and crypto wallets

### ISSUE THREAD

**Issue by janedanyid** [FallenAstaroth/stink#43]
Whether it can be increased. Steal Crypto Wallet exe. browser extension.?

**Comment by FallenAstaroth** [comment]
I was just thinking about what I could add. I think I'll do it in a future update.

**Comment by FallenAstaroth** [comment]
Browser extensions collecting added.

https://github.com/FallenAstaroth/stink/releases/tag/v2.8.0

**Comment by FallenAstaroth** [comment]
> What extensions does it collect?

Right now it just collects a list of installed extensions. In the next update I will add crypto wallet collection.

**Comment by FallenAstaroth** [comment]
Added Metamask extension collecting. Other wallets will be added later.

https://github.com/FallenAstaroth/stink/releases/tag/v3.1.0
