### ISSUE TITLE
I can't create exe file

### ISSUE THREAD

**Issue by Keni0lez** [FallenAstaroth/stink#44]
C:\Users\User>C:\Users\User\Desktop\stink-master\stink-master\compiler.bat
File name for compilation (for example test.py): gog
Compress the file? (y/n): y
Disable console? (y/n): y

C:\Users\User>pip install virtualenv   & virtualenv venv   & call venv\Scripts\activate
Requirement already satisfied: virtualenv in c:\users\User\appdata\local\programs\python\python311\lib\site-packages (20.21.0)
Requirement already satisfied: distlib<1,>=0.3.6 in c:\users\User\appdata\local\programs\python\python311\lib\site-packages (from virtualenv) (0.3.6)
Requirement already satisfied: filelock<4,>=3.4.1 in c:\users\User\appdata\local\programs\python\python311\lib\site-packages (from virtualenv) (3.10.4)
Requirement already satisfied: platformdirs<4,>=2.4 in c:\users\User\appdata\local\programs\python\python311\lib\site-packages (from virtualenv) (3.1.1)
created virtual environment CPython3.11.2.final.0-64 in 1427ms
  creator CPython3Windows(dest=C:\Users\User\venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\User\AppData\Local\pypa\virtualenv)
    added seed packages: Nuitka==0.6.19.6, pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

(venv) C:\Users\User>pip install -r requirements.txt   & pip install Nuitka==0.6.19.6
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Requirement already satisfied: Nuitka==0.6.19.6 in c:\users\User\venv\lib\site-packages (0.6.19.6)

(venv) C:\Users\User>if "y" == "y" (pip install zstandard==0.17.0 )  else (echo Y  | pip uninstall zstandard )
Collecting zstandard==0.17.0
  Using cached zstandard-0.17.0.tar.gz (629 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 485, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 90, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-ow2c37e5\zstandard_fbb712d6ea0041b1b12ae868daddfbc5\setup_zstd.py", line 66, in get_c_extension
          compiler.initialize()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\msvc.py", line 210, in msvc14_get_vc_env
          return _msvc14_get_vc_env(plat_spec)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-edrcvoi4\overlay\Lib\site-packages\setuptools\msvc.py", line 164, in _msvc14_get_vc_env
          raise distutils.errors.DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

(venv) C:\Users\User>if "y" == "y" (nuitka --onefile --plugin-enable=multiprocessing --windows-disable-console gog )  else (nuitka --onefile --plugin-enable=multiprocessing gog )
Nuitka-Options:INFO: Used command line options: --onefile --plugin-enable=multiprocessing --windows-disable-console gog
Nuitka:WARNING: The version '3.11' is not currently supported. Expect problems.
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.6' on Python '3.11' commercial None.
FATAL: __main__.py: can't open file 'gog'.

**Comment by Keni0lez** [comment]
I uninstalled python 3.11 and install python 3.9

and error another:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
Requirement already satisfied: Nuitka==0.6.19.6 in c:\users\keni\venv\lib\site-packages (0.6.19.6)

(venv) C:\Users\Keni>if "n" == "y" (pip install zstandard==0.17.0 )  else (echo Y  | pip uninstall zstandard )
WARNING: Skipping zstandard as it is not installed.

(venv) C:\Users\Keni>if "y" == "y" (nuitka --onefile --plugin-enable=multiprocessing --windows-disable-console fff )  else (nuitka --onefile --plugin-enable=multiprocessing fff )
Nuitka-Options:INFO: Used command line options: --onefile --plugin-enable=multiprocessing --windows-disable-console fff
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.6' on Python '3.9' commercial None.
FATAL: __main__.py: can't open file 'test.py'.

**Comment by FallenAstaroth** [comment]
> I uninstalled python 3.11 and install python 3.9
> 
> and error another:
> 
> ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' Requirement already satisfied: Nuitka==0.6.19.6 in c:\users\keni\venv\lib\site-packages (0.6.19.6)
> 
> (venv) C:\Users\Keni>if "n" == "y" (pip install zstandard==0.17.0 ) else (echo Y | pip uninstall zstandard ) WARNING: Skipping zstandard as it is not installed.
> 
> (venv) C:\Users\Keni>if "y" == "y" (nuitka --onefile --plugin-enable=multiprocessing --windows-disable-console fff ) else (nuitka --onefile --plugin-enable=multiprocessing fff ) Nuitka-Options:INFO: Used command line options: --onefile --plugin-enable=multiprocessing --windows-disable-console fff Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.6' on Python '3.9' commercial None. FATAL: **main**.py: can't open file 'test.py'.

Make sure that the path to the file is correct / the file is in the same directory as `compiler.bat`. I also see that you have a problem reading the `requirements.txt`, which means you are running it from a different directory, or you deleted it. 

Download the archive with `stink`, unzip it and create a `test.py` file in the same directory as `compiler.bat`, `requirements.txt`, etc.

**Comment by Keni0lez** [comment]
thank u, i fixed it ❤
