### ISSUE TITLE
Collecting steam session 

### ISSUE THREAD

**Issue by Keni0lez** [FallenAstaroth/stink#45]
Hi! Can u add steal steam sessions?

**Comment by FallenAstaroth** [comment]
> Hi! Can u add steal steam sessions?

Hi. I will take care of this issue after adding crypto wallet collecting

**Comment by FallenAstaroth** [comment]
Steam collecting added in the new version.

https://github.com/FallenAstaroth/stink/releases/tag/v3.3.0
