### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by EDown2k** [FallenAstaroth/stink#46]
Amazing work on this gem! Just wondering about cookies for Chrome. When importing json cookies via Chrome extensions it doesn't seem to work. Firefox cookies work great. Anyone facing the same issue or know of a solution?

**Comment by FallenAstaroth** [comment]
> Amazing work on this gem! Just wondering about cookies for Chrome. When importing json cookies via Chrome extensions it doesn't seem to work. Firefox cookies work great. Anyone facing the same issue or know of a solution?

Thank you) Are you using the same extensions to import? If not, maybe it's because there are slightly different import formats.

**Comment by EDown2k** [comment]
> > Amazing work on this gem! Just wondering about cookies for Chrome. When importing json cookies via Chrome extensions it doesn't seem to work. Firefox cookies work great. Anyone facing the same issue or know of a solution?
> 
> Thank you) Are you using the same extensions to import? If not, maybe it's because there are slightly different import formats.

No, on Firefox an extension called "Cookie Quick Manager" works well. On Chrome, I've tried about 10 different extension and none of them seem to work. I've formatted the cookies to correct JSON as well as simply copy/pasting the JSON provided and still no luck. Could you recommend any extensions or alternatives to import Chrome cookies?

**Comment by FallenAstaroth** [comment]
> > > Amazing work on this gem! Just wondering about cookies for Chrome. When importing json cookies via Chrome extensions it doesn't seem to work. Firefox cookies work great. Anyone facing the same issue or know of a solution?
> > 
> > 
> > Thank you) Are you using the same extensions to import? If not, maybe it's because there are slightly different import formats.
> 
> No, on Firefox an extension called "Cookie Quick Manager" works well. On Chrome, I've tried about 10 different extension and none of them seem to work. I've formatted the cookies to correct JSON as well as simply copy/pasting the JSON provided and still no luck. Could you recommend any extensions or alternatives to import Chrome cookies?

I can't tell you now, because I wrote this functionality more than a year ago. As soon as I have time, I will test it and report the results.

**Comment by EDown2k** [comment]
Thank you. I think it may be related to how Chrome handles cookies now. Appreciate your work.

**Comment by ChazGTP** [comment]
I have the same issue. Everything works great except for the cookies. Has there been any resolution to this? The json file seems to be improperly formatted or something.

**Comment by QuangTuyeens** [comment]
u need convert cookie type, still using netscape cookie but shorten like this 
name=value;name2=value2

**Comment by EDown2k** [comment]
> u need convert cookie type, still using netscape cookie but shorten like this name=value;name2=value2

Please elaborate. Is there a tool that can do this or can you show me an example? Thx!

**Comment by EDown2k** [comment]
Did anyone have any luck figuring out how to get cookies to work here? Thanks!

**Comment by EDown2k** [comment]
I've tried this method plus many others. This works with every other stealer I've used except for Stink. I've tried with 50+ different json cookie files and multiple cookie editors including Cookiebro.

In Step 3 (Prepare json file with cookies). The file is already in json format. I open them and make sure there are not commented lines with # as well. Has anyone been able to get cookie import to work with Stink?

**Comment by FallenAstaroth** [comment]
> I've tried this method plus many others. This works with every other stealer I've used except for Stink. I've tried with 50+ different json cookie files and multiple cookie editors including Cookiebro.
> 
> In Step 3 (Prepare json file with cookies). The file is already in json format. I open them and make sure there are not commented lines with # as well. Has anyone been able to get cookie import to work with Stink?

Can you give me an example of an open-source stealer where cookies work fine through these extensions? I will compare them and try to determine the cause.

**Comment by EDown2k** [comment]
Yes, sure. Please see https://github.com/can-kat/cstealer
The cookies are in a different format, but work well. Thx

**Comment by FallenAstaroth** [comment]
Tested on [this extension](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm).

1. Pull all lines from the desired site from the cookies file.
2. Go to the site for which you want to import cookies.
3. Open the import tab of the extension.
4. Insert a cookie and click the import button.
5. Reload the page.

**Comment by EDown2k** [comment]
Thanks so much! It seems this update doesn't bypass WD but still the cookies functionality works.
