### ISSUE TITLE
I founded bug 👍 

### ISSUE THREAD

**Issue by EndFixed** [FallenAstaroth/stink#47]
need to add time.sleep(5) to telegram sender because .zip file slowly gathers and the request manages to leave without it. as a result i got error 400 from telegram api.

**Comment by FallenAstaroth** [comment]
I need to verify this information. The archive is collected in the same thread and process as the sender, so I doubt that's the problem, since they are executed in turn.

**Comment by QuangTuyeens** [comment]
@FallenAstaroth do you have guiding video, i cant set up stink :(((

**Comment by FallenAstaroth** [comment]
During the tests, the problem did not reproduce, the archive is sent only after a full creation. The tests were performed on 4 different computers, with different settings and parameters.
