### ISSUE TITLE
Fail with stealing 

### ISSUE THREAD

**Issue by TheBogler** [FallenAstaroth/stink#49]
Привет! Я имею ошибку с Microsoft edge и еще с Steam и FileZilla
[Microsoft Edge]: OperationalError('no such table: cookies')
[FileZilla]: FileNotFoundError(2, 'No such file or directory')
[Steam]: PermissionError(13, 'Permission denied')
[Microsoft Edge]: OperationalError('no such table: cookies')

**Comment by FallenAstaroth** [comment]
> 1. последнюю
> 2. Нет

А какая версия Windows

**Comment by TheBogler** [comment]
10

**Comment by FallenAstaroth** [comment]
FileZilla пофиксил, оно продолжит выводить ошибку, так как один из файлов не всегда создается, но при этом соберет все хосты.

Другие проблемы еще тестирую.

Steam у тебя в какой директории установлен? В Edge есть еще профили?

**Comment by FallenAstaroth** [comment]
Недостаточно информации для воспроизведения.
