### ISSUE TITLE
The newest version of Stink has a problem

### ISSUE THREAD

**Issue by TMQrX** [FallenAstaroth/stink#54]
When I run the stealer after building by stink package, my browser edge suddenlly shutdown and the stealer didn;t work anymore. I already checked the process hacker 2 and the result that the process of stealer run ~3 sec and terminate. It worked on my pc but when I test in my laptop the problem appears

**Comment by FallenAstaroth** [comment]
It's a defense against debagging. Stiller will not work if one of the blacklisted programs is running. You can disable the check by passing the `protectors=[Protectors.disable]` parameter to `Stealer`

Example:
https://github.com/FallenAstaroth/stink/wiki/Anti%E2%80%90debugging-and-anti%E2%80%90virtual%E2%80%90machine

**Comment by FallenAstaroth** [comment]
If after disabling it continues to close - open it via console and send what it outputs

**Comment by linhka1999** [comment]
Have the same problem. I already disable but the stealer didn't working

**Comment by linhka1999** [comment]
![image](https://github.com/FallenAstaroth/stink/assets/38876387/72d7eb25-46b6-4d83-a784-1e948ea9d880)

**Comment by FallenAstaroth** [comment]
> ![image](https://user-images.githubusercontent.com/38876387/279362452-72d7eb25-46b6-4d83-a784-1e948ea9d880.png)

Removed SSL certificate verification. Upgrade to the latest version and create a new build.

**Comment by linhka1999** [comment]
How can i remove it ? btw the stink i use is the lastest version

**Comment by FallenAstaroth** [comment]
> How can i remove it ? btw the stink i use is the lastest version

I've already removed the validation, the problem should go away. Are you using version 4.4.1?
